// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Blog post documents
 */
interface BlogPostDocumentData {
  /**
   * Title field in *Blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Blog post title
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Blog post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Blog post desc
   * - **API ID Path**: blog_post.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Content field in *Blog post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Blog post content
   * - **API ID Path**: blog_post.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Featured image field in *Blog post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Publication date field in *Blog post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.publication_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publication_date: prismic.DateField;
}

/**
 * Blog post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

/**
 * Item in *Habit → Benefits*
 */
export interface HabitDocumentDataBenefitsItem {
  /**
   * Benefit Description field in *Habit → Benefits*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: habit.benefits[].benefit
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  benefit: prismic.KeyTextField;
}

/**
 * Content for Habit documents
 */
interface HabitDocumentData {
  /**
   * Habit Name field in *Habit*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter habit name
   * - **API ID Path**: habit.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Description field in *Habit*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Describe the habit
   * - **API ID Path**: habit.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Main Image field in *Habit*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: habit.main_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Benefits field in *Habit*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: habit.benefits[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  benefits: prismic.GroupField<Simplify<HabitDocumentDataBenefitsItem>>;

  /**
   * Difficulty Level field in *Habit*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select difficulty
   * - **API ID Path**: habit.difficulty_level
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  difficulty_level: prismic.SelectField<
    "Beginner" | "Intermediate" | "Advanced"
  >;

  /**
   * Implementation Tips field in *Habit*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: habit.implementation_tips
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  implementation_tips: prismic.RichTextField;

  /**
   * category field in *Habit*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: habit.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<"habit_category">;
}

/**
 * Habit document from Prismic
 *
 * - **API ID**: `habit`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HabitDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HabitDocumentData>, "habit", Lang>;

/**
 * Item in *Habit Categories → categories*
 */
export interface HabitCategoriesDocumentDataCategoriesItem {
  /**
   * category_name field in *Habit Categories → categories*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: habit_categories.categories[].category_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category_name: prismic.KeyTextField;
}

/**
 * Content for Habit Categories documents
 */
interface HabitCategoriesDocumentData {
  /**
   * categories field in *Habit Categories*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: habit_categories.categories[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  categories: prismic.GroupField<
    Simplify<HabitCategoriesDocumentDataCategoriesItem>
  >;
}

/**
 * Habit Categories document from Prismic
 *
 * - **API ID**: `habit_categories`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HabitCategoriesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HabitCategoriesDocumentData>,
    "habit_categories",
    Lang
  >;

/**
 * Content for Habit Category documents
 */
interface HabitCategoryDocumentData {
  /**
   * Name field in *Habit Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: habit_category.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * description field in *Habit Category*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: habit_category.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Habit Category document from Prismic
 *
 * - **API ID**: `habit_category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HabitCategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HabitCategoryDocumentData>,
    "habit_category",
    Lang
  >;

type HomepageDocumentDataSlicesSlice = CallToActionSlice | TestSliceSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Homepage image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.homepage_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  homepage_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Navigation → Navigation items*
 */
export interface NavigationDocumentDataNavigationItemsItem {
  /**
   * title field in *Navigation → Navigation items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navigation_items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * page field in *Navigation → Navigation items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navigation_items[].page
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page: prismic.KeyTextField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Navigation items field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navigation_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation_items: prismic.GroupField<
    Simplify<NavigationDocumentDataNavigationItemsItem>
  >;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice = AppDemoBlockSlice | CallToAction2Slice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | BlogPostDocument
  | HabitDocument
  | HabitCategoriesDocument
  | HabitCategoryDocument
  | HomepageDocument
  | NavigationDocument
  | PageDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogPostDocument,
      BlogPostDocumentData,
      HabitDocument,
      HabitDocumentData,
      HabitDocumentDataBenefitsItem,
      HabitCategoriesDocument,
      HabitCategoriesDocumentData,
      HabitCategoriesDocumentDataCategoriesItem,
      HabitCategoryDocument,
      HabitCategoryDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataNavigationItemsItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
